name: Test-Actions

on:
  push:
    branches:
      - "citest/*"
    tags:
      - "v*"

jobs:
  build_and_release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/ci/')  || startsWith(github.ref, 'refs/heads/citest/') }}
    steps:
      - uses: actions/checkout@v2
      - name: Set Yak Version by Tag
        uses: mad9000/actions-find-and-replace-string@1
        id: fetchtag
        with:
          source: ${{ github.ref }}
          find: 'refs/tags/'
          replace: ''
      - name: Print RELEASE_VERSION
        run: |
          echo "github actions's env VERSION: ${{ steps.fetchtag.outputs.value }}"
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.3
      #      - name: Download Npcap SDK (Windows)
      #        run: |
      #          Invoke-WebRequest https://nmap.org/npcap/dist/npcap-sdk-1.07.zip -OutFile C:\NpcapSDK.zip
      #          Expand-Archive C:\NpcapSDK.zip -DestinationPath ..\wpdpack
      #        if: runner.os == 'Windows'
      - name: echo citest.txt
        run: |
          echo "citest.txt" > citest.txt
      - name: Upload yak to oss Latest
        uses: tvrcgo/upload-to-oss@master
        with:
          key-id: ${{ secrets.OSS_KEY_ID }}
          key-secret: ${{ secrets.OSS_KEY_SECRET }}
          region: oss-accelerate
          bucket: yaklang
          assets: |
            ./citest.txt:/citest.txt